version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - gravity-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - DATABASE_URL=./data/downloads.db
      - DOWNLOAD_PATH=./downloads
      - MAX_CONCURRENT_DOWNLOADS=3
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - ./downloads:/app/downloads
      - ./data:/app/data
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - gravity-network

  # Redis 服务（用于任务队列）
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gravity-network

  # Nginx 反向代理（可选，用于生产环境）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - gravity-network
    profiles:
      - production

volumes:
  redis_data:

networks:
  gravity-network:
    driver: bridge 