#!/usr/bin/env python3
"""
Chrome Cookies导出工具

使用方法：
1. 确保Chrome浏览器已关闭
2. 运行此脚本
3. 选择要导出的域名
4. cookies将保存为Netscape格式的txt文件
"""

import os
import sqlite3
import json
from pathlib import Path
from datetime import datetime
import platform

def find_chrome_cookies_db():
    """查找Chrome的Cookies数据库文件"""
    system = platform.system()
    
    if system == "Darwin":  # macOS
        cookies_path = Path.home() / "Library/Application Support/Google/Chrome/Default/Cookies"
    elif system == "Windows":
        cookies_path = Path.home() / "AppData/Local/Google/Chrome/User Data/Default/Cookies"
    elif system == "Linux":
        cookies_path = Path.home() / ".config/google-chrome/Default/Cookies"
    else:
        raise Exception(f"不支持的操作系统: {system}")
    
    if not cookies_path.exists():
        raise Exception(f"Chrome cookies文件不存在: {cookies_path}")
    
    return cookies_path

def export_cookies_for_domain(domain, output_file):
    """导出指定域名的cookies为Netscape格式"""
    cookies_db = find_chrome_cookies_db()
    
    # 复制数据库文件到临时位置（因为Chrome可能正在使用）
    temp_db = Path("/tmp/chrome_cookies_temp.db")
    import shutil
    shutil.copy2(cookies_db, temp_db)
    
    try:
        conn = sqlite3.connect(temp_db)
        cursor = conn.cursor()
        
        # 查询指定域名的cookies
        query = """
        SELECT host_key, name, value, path, expires_utc, is_secure, is_httponly
        FROM cookies 
        WHERE host_key LIKE ?
        ORDER BY host_key, name
        """
        
        cursor.execute(query, (f"%{domain}%",))
        cookies = cursor.fetchall()
        
        if not cookies:
            print(f"未找到域名 {domain} 的cookies")
            return False
        
        # 写入Netscape格式的cookies文件
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by Chrome Cookies Export Tool\n")
            f.write(f"# Domain: {domain}\n")
            f.write(f"# Exported: {datetime.now().isoformat()}\n\n")
            
            for cookie in cookies:
                host_key, name, value, path, expires_utc, is_secure, is_httponly = cookie
                
                # 转换Chrome的时间戳格式
                if expires_utc:
                    # Chrome使用微秒，转换为秒
                    expires = int(expires_utc / 1000000) - 11644473600  # Chrome epoch offset
                else:
                    expires = 0
                
                # Netscape格式: domain, domain_specified, path, secure, expires, name, value
                domain_specified = "TRUE" if host_key.startswith('.') else "FALSE"
                secure = "TRUE" if is_secure else "FALSE"
                
                line = f"{host_key}\t{domain_specified}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
                f.write(line)
        
        conn.close()
        print(f"成功导出 {len(cookies)} 个cookies到 {output_file}")
        return True
        
    except Exception as e:
        print(f"导出cookies失败: {e}")
        return False
    finally:
        # 清理临时文件
        if temp_db.exists():
            temp_db.unlink()

def main():
    """主函数"""
    print("🍪 Chrome Cookies 导出工具")
    print("=" * 40)
    
    # 检查Chrome cookies数据库
    try:
        cookies_db = find_chrome_cookies_db()
        print(f"找到Chrome cookies数据库: {cookies_db}")
    except Exception as e:
        print(f"错误: {e}")
        return
    
    # 预设的常用域名
    common_domains = {
        '1': ('bilibili.com', 'Bilibili'),
        '2': ('youtube.com', 'YouTube'),
        '3': ('twitter.com', 'Twitter'),
        '4': ('facebook.com', 'Facebook'),
        '5': ('instagram.com', 'Instagram')
    }
    
    print("\n选择要导出的网站:")
    for key, (domain, name) in common_domains.items():
        print(f"  {key}. {name} ({domain})")
    print("  6. 自定义域名")
    
    choice = input("\n请选择 (1-6): ").strip()
    
    if choice in common_domains:
        domain, site_name = common_domains[choice]
    elif choice == '6':
        domain = input("请输入域名 (如: example.com): ").strip()
        site_name = domain
    else:
        print("无效选择")
        return
    
    # 确保cookies目录存在
    cookies_dir = Path("../cookies")
    cookies_dir.mkdir(exist_ok=True)
    
    # 生成输出文件名
    safe_domain = domain.replace('.', '_')
    output_file = cookies_dir / f"{safe_domain}_cookies.txt"
    
    print(f"\n开始导出 {site_name} 的cookies...")
    print("请确保Chrome浏览器已经关闭！")
    input("按Enter键继续...")
    
    if export_cookies_for_domain(domain, output_file):
        print(f"\n✅ 导出成功！")
        print(f"文件保存在: {output_file}")
        print(f"\n现在你可以在API中使用:")
        print(f'  "cookies_file": "{output_file}"')
    else:
        print("\n❌ 导出失败！")

if __name__ == "__main__":
    main() 